### PR TITLE
Updates to my own plugin + other fixed

### PR DESCRIPTION
**Pull request by Eventyret**
- Update my own plugin to 1.4.0 (Please see it's own repo for what has changed)
- Added `pylint, pep8, autopep8, pylint-flask pylint-django` this should help students follow pep8 within MS3 and MS4
- Added toggle in `.theia/settings.json` please inform students that they can switch between `pylint_flask` and  `pylint_django` in this file to get support for pep8 and auto-formatting.
- Added error lens to project this should highlight lines for students helping them adhering to standards.

### CODE REVIEW

**Comment by lechien73** [comment]
Query before I approve the PR, has this been tested to make sure that the "Linter is not installed" message doesn't come up again?

**Comment by Eventyret** [comment]
I will make a quick test on this just to find out @lechien73 will let you know

**Comment by Eventyret** [comment]
You are right @lechien73 It seems that there is a issue with pylint not been recognized. I will roll that back and leave the two plugins installed first. Ill create a separate PR for the pylint if I can get the workaround later to work.

**Comment by Eventyret** [comment]
So this should just show the students more how it is and flake8 does have a linter for Django and flask which should add support for it.

**Pull request merged**
